import { Nav } from '@/components/NavMenu/Nav'
import { Providers } from '@/components/layout/providers'
import { Roboto } from 'next/font/google'
import './globals.css'

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '700', '900'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  keywords: ['Next.js', 'React', 'Web Development'],
  author: 'Kyaw Za Yan Naing',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={` dark:bg-primary`}>
        <Providers>
          <Nav />
          <div className={roboto.className}>
            <main className="px-12">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  )
}
