import { Nav } from '@/components/NavMenu/Nav'
import { Providers } from '@/components/Providers/providers'
import './globals.css'
import { ReactNode } from 'react'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  keywords: ['Next.js', 'React', 'Web Development'],
  author: 'Kyaw Za Yan Naing',
}

type RootLayoutProps = {
  children: ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="h-screen font-ibm_plex_sans dark:bg-primary">
            <Nav />
            <main className="px-12">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  )
}
